import { useState, useEffect } from 'react';

const TYPE_CONFIG = {
  trade_open:  { icon: '🟢', label: 'ENTRADA',  color: '#4ade80', bg: 'rgba(74,222,128,0.08)',  border: 'rgba(74,222,128,0.2)' },
    trade_close: { icon: '🔴', label: 'CIERRE',   color: '#f87171', bg: 'rgba(248,113,113,0.08)', border: 'rgba(248,113,113,0.2)' },
      alert:       { icon: '⚠️', label: 'ALERTA',   color: '#fb923c', bg: 'rgba(251,146,60,0.08)',  border: 'rgba(251,146,60,0.2)' },
        analysis:    { icon: '📊', label: 'ANÁLISIS', color: '#38bdf8', bg: 'rgba(56,189,248,0.08)',  border: 'rgba(56,189,248,0.2)' },
          info:        { icon: 'ℹ️', label: 'INFO',     color: '#94a3b8', bg: 'rgba(148,163,184,0.06)', border: 'rgba(148,163,184,0.1)' },
          };

          function timeAgo(iso) {
            const diff = (Date.now() - new Date(iso)) / 1000;
              if (diff < 60)  return 'ahora mismo';
                if (diff < 3600) return `hace ${Math.floor(diff/60)}m`;
                  if (diff < 86400) return `hace ${Math.floor(diff/3600)}h`;
                    return new Date(iso).toLocaleDateString('es-AR');
                    }

                    function playSound() {
                      try {
                          const ctx = new (window.AudioContext || window.webkitAudioContext)();
                              const osc = ctx.createOscillator();
                                  const gain = ctx.createGain();
                                      osc.connect(gain);
                                          gain.connect(ctx.destination);
                                              osc.frequency.value = 880;
                                                  osc.type = 'sine';
                                                      gain.gain.setValueAtTime(0.3, ctx.currentTime);
                                                          gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.4);
                                                              osc.start(ctx.currentTime);
                                                                  osc.stop(ctx.currentTime + 0.4);
                                                                    } catch {}
                                                                    }

                                                                    export default function Home() {
                                                                      const [notifications, setNotifications] = useState([]);
                                                                        const [lastCount, setLastCount] = useState(0);
                                                                          const [online, setOnline] = useState(false);
                                                                            const [clock, setClock] = useState('');

                                                                              useEffect(() => {
                                                                                  const t = setInterval(() => setClock(new Date().toLocaleTimeString('es-AR')), 1000);
                                                                                      return () => clearInterval(t);
                                                                                        }, []);

                                                                                          async function fetchNotifications() {
                                                                                              try {
                                                                                                    const res = await fetch('/api/notifications');
                                                                                                          const data = await res.json();
                                                                                                                setOnline(true);
                                                                                                                      if (data.length > lastCount && lastCount > 0) {
                                                                                                                              playSound();
                                                                                                                                      if (Notification.permission === 'granted' && data[0]) {
                                                                                                                                                new Notification('Claude Trading Bot', { body: data[0].message });
                                                                                                                                                        }
                                                                                                                                                              }
                                                                                                                                                                    setLastCount(data.length);
                                                                                                                                                                          setNotifications(data);
                                                                                                                                                                              } catch { setOnline(false); }
                                                                                                                                                                                }
                                                                                                                                                                                
                                                                                                                                                                                  useEffect(() => {
                                                                                                                                                                                      if ('Notification' in window && Notification.permission === 'default') {
                                                                                                                                                                                            Notification.requestPermission();
                                                                                                                                                                                                }
                                                                                                                                                                                                    fetchNotifications();
                                                                                                                                                                                                        const t = setInterval(fetchNotifications, 5000);
                                                                                                                                                                                                            return () => clearInterval(t);
                                                                                                                                                                                                              }, [lastCount]);
                                                                                                                                                                                                              
                                                                                                                                                                                                                const css = `
                                                                                                                                                                                                                    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
                                                                                                                                                                                                                        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #080d1a; color: #e2e8f0; min-height: 100vh; -webkit-font-smoothing: antialiased; }
                                                                                                                                                                                                                            .container { max-width: 560px; margin: 0 auto; padding: 20px 16px 40px; }
                                                                                                                                                                                                                                header { display: flex; justify-content: space-between; align-items: center; padding-bottom: 16px; border-bottom: 1px solid rgba(148,163,184,0.08); margin-bottom: 24px; }
                                                                                                                                                                                                                                    .logo { display: flex; align-items: center; gap: 10px; }
                                                                                                                                                                                                                                        .logo-icon { width: 32px; height: 32px; border-radius: 9px; background: linear-gradient(135deg, #fb923c, #f59e0b); display: flex; align-items: center; justify-content: center; font-size: 16px; font-weight: 800; color: white; }
                                                                                                                                                                                                                                            .logo-name { font-size: 15px; font-weight: 600; }
                                                                                                                                                                                                                                                .logo-sub { font-size: 11px; color: #475569; margin-top: 1px; }
                                                                                                                                                                                                                                                    .header-right { display: flex; align-items: center; gap: 12px; }
                                                                                                                                                                                                                                                        .clock { font-size: 12px; color: #475569; font-variant-numeric: tabular-nums; }
                                                                                                                                                                                                                                                            .dot { width: 6px; height: 6px; border-radius: 50%; background: currentColor; box-shadow: 0 0 6px currentColor; animation: pulse 2s ease-in-out infinite; }
                                                                                                                                                                                                                                                                @keyframes pulse { 0%,100%{opacity:1} 50%{opacity:.35} }
                                                                                                                                                                                                                                                                    .empty { text-align: center; padding: 60px 20px; color: #475569; font-size: 13px; }
                                                                                                                                                                                                                                                                        .empty-icon { font-size: 36px; margin-bottom: 12px; opacity: .4; }
                                                                                                                                                                                                                                                                            .notif-list { display: flex; flex-direction: column; gap: 10px; }
                                                                                                                                                                                                                                                                                .notif-card { border-radius: 12px; padding: 14px 16px; border: 1px solid; animation: slideIn .25s ease; }
                                                                                                                                                                                                                                                                                    @keyframes slideIn { from{opacity:0;transform:translateY(-6px)} to{opacity:1;transform:translateY(0)} }
                                                                                                                                                                                                                                                                                        .notif-header { display: flex; align-items: center; justify-content: space-between; margin-bottom: 6px; }
                                                                                                                                                                                                                                                                                            .notif-badge { display: inline-flex; align-items: center; gap: 5px; font-size: 10px; font-weight: 700; letter-spacing: .5px; padding: 2px 8px; border-radius: 4px; background: rgba(255,255,255,.06); }
                                                                                                                                                                                                                                                                                                .notif-time { font-size: 10px; color: #475569; }
                                                                                                                                                                                                                                                                                                    .notif-msg { font-size: 13px; line-height: 1.55; color: #cbd5e1; }
                                                                                                                                                                                                                                                                                                        .notif-meta { margin-top: 8px; display: flex; gap: 10px; font-size: 11px; color: #64748b; }
                                                                                                                                                                                                                                                                                                            .meta-tag { background: rgba(255,255,255,.04); padding: 2px 7px; border-radius: 4px; font-variant-numeric: tabular-nums; }
                                                                                                                                                                                                                                                                                                                .section-title { font-size: 10px; letter-spacing: 1px; text-transform: uppercase; color: #475569; font-weight: 500; margin-bottom: 12px; }
                                                                                                                                                                                                                                                                                                                  `;
                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                                                                        <>
                                                                                                                                                                                                                                                                                                                              <style>{css}</style>
                                                                                                                                                                                                                                                                                                                                    <div className="container">
                                                                                                                                                                                                                                                                                                                                            <header>
                                                                                                                                                                                                                                                                                                                                                      <div className="logo">
                                                                                                                                                                                                                                                                                                                                                                  <div className="logo-icon">₿</div>
                                                                                                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                                                                                            <div className="logo-name">Claude Trading Bot</div>
                                                                                                                                                                                                                                                                                                                                                                                                          <div className="logo-sub">Notificaciones en tiempo real</div>
                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="header-right">
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{display:'flex',alignItems:'center',gap:5,fontSize:11,fontWeight:500,color:online?'#4ade80':'#f87171'}}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="dot" style={{background:online?'#4ade80':'#f87171'}}></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {online ? 'Online' : 'Offline'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="clock">{clock}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </header>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {notifications.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="empty">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="empty-icon">🤖</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Sin notificaciones todavía.<br />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Claude te avisará acá cuando tome una decisión.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="section-title">'Últimas acciones</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="notif-list">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {notifications.map(n => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const cfg = TYPE_CONFIG[n.type] || TYPE_CONFIG.info;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div key={n.id} className="notif-card" style={{background:cfg.bg,borderColor:cfg.border}}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="notif-header">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className="notif-badge" style={{color:cfg.color}}>{cfg.icon} {cfg.label}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span className="notif-time">{timeAgo(n.timestamp)}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="notif-msg">{n.message}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {(n.pnl || n.price || n.action) && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="notif-meta">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {n.price && <span className="meta-tag">💲 ${Number(n.price).toLocaleString('en-US',{minimumFractionDigits:2})}</span>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {n.pnl && <span className="meta-tag" style={{color:n.pnl>0?'#4ade80':'#f87171'}}>{n.pnl>0?'+':''}{n.pnl} USDT</span>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {n.action && <span className="meta-tag">{n.action}</span>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
